#!/bin/bash

declare MYAPT=`echo ~/.myapt`
declare MYDIR=~/.myfile
declare MYLOG=~/.myfilelog


sudo apt-get update
if [ -f ${MYAPT} ]; then
  cat ${MYAPT} | while read PKG; do
    dpkg -l "${PKG}" >/dev/null 2>&1
    if [ ${?} != 0 ]; then
      sudo apt-get install -y --no-install-recommends "${PKG}"
    fi
  done
fi

if [ -f ${MYLOG} -a -d ${MYDIR} ]; then
  cat ${MYLOG} | while read line; do
    FPATH=${line//,*}
    SPATH=${line##*,}
    if [ -f ${SPATH} ]; then
      rm ${SPATH}
    fi

    ln -s ${FPATH} ${SPATH}
    FUID=`stat -c '%U' ${FPATH}`
    FGID=`stat -c '%G' ${FPATH}`
    chown -h $FUID:$FGID ${SPATH}
  done
fi
