#!/bin/bash

declare MYAPT=/home/hogemin/.myapt
declare MYPIP=/home/hogemin/.mypip
declare MYDIR=/home/hogemin/.myfile
declare MYLOG=/home/hogemin/.myfilelog


sudo apt-get update
if [ -f ${MYAPT} ]; then
  cat ${MYAPT} | while read PKG; do
    dpkg -l "${PKG}" >/dev/null 2>&1
    if [ ${?} != 0 ]; then
      sudo apt-get install -y --no-install-recommends "${PKG}"
    fi
  done
fi

rm -rf ~/.local
if [ -f ${MYPIP} ]; then
  cat ${MYPIP} | while read PKG; do
    pip3 show "${PKG}" >/dev/null 2>&1
    if [ ${?} != 0 ]; then
      pip3 install -q "${PKG}"
    fi
  done
fi

if [ -f ${MYLOG} -a -d ${MYDIR} ]; then
  cat ${MYLOG} | while read line; do
    FPATH=${line//,*}
    SPATH=${line##*,}
    if [ -f ${SPATH} ]; then
      rm ${SPATH}
    fi

    sudo ln -s ${FPATH} ${SPATH}

    FUID=`stat -c '%U' ${FPATH}`
    FGID=`stat -c '%G' ${FPATH}`
    sudo chown -h $FUID:$FGID ${SPATH}
  done
fi

exit 0
