#!/bin/bash

# Check inputs
declare MYAPT=/home/hogemin/.myapt

# Install
for PKG in "$@"
do
  dpkg -l "${PKG}" | grep '^ii' >/dev/null 2>&1
  if [ ${?} != 0 ]; then
    sudo apt-get install -y --no-install-recommends "${PKG}"
    if [ ${?} == 0 ]; then
      echo "${PKG}" >> "${MYAPT}"
    fi
  else
    echo "Already installed. Exit."
  fi
done
