#!/bin/bash

# Usage
usage_exit() {
  echo "USAGE: $0 <container-name>"

  exit 1
}

# Constants
local MODE, REMOVE, MYDC, MYHOME, MYTMPL

# Check Input
while getopts hr OPT
do
    case $OPT in
        r)  REMOVE="true"
            ;;
        h)  usage_exit
            ;;
        \?) usage_exit
            ;;
    esac
done

# Inputs
shift $((OPTIND - 1))
CNAME=$1
if [ "${CNAME}" = "" ]; then
    usage_exit
fi

# Check Environment
MYDC=`echo ~/.mydc`
if [ -d "${MYDC} ]; then
    echo "${MYDC} does not exists. Exit."
    exit 1
fi


# Main

CID=`docker ps -a -q -f "name=^${CNAME}$" -f "ancestor=mydc"`
if [ "${REMOVE}" == "true" ]; then
    MODE = "remove"
elif [ ${CID} != "" ]; then
    MODE="create"
else
    MODE="run"
fi

if [ ${MODE} = "remove" ]; then
    docker rm ${CNAME}
elif [ ${MODE} = "create" ]; then
    MYHOME=${MYDC}/${CNAME}
    MYTMPL=${MYDC}/template

    cp -r ${MYTMPL} ${MYHOME}
    docker run -it -h ${CNAME} \
        -v ${MYHOME}:/home/hogemin \
        -v ${PWD}:/vol \
        --name ${CNAME} mydc:latest
else
    docker start -i ${CID}
fi
